Modular setup & docs
MILA-Wien/collectivo pull request #118
Opened 2023-05-26 11:07 UTC by JoelForamitti

- Allow for configuration of collectivo via a collectivo.yml file.
- Allow for configuration of extensinos via an extension.yml file.
- Remove all custom MILA extensions from the main repository.
- Start a documentation with [mkdocs-material](https://squidfunk.github.io/mkdocs-material/)
- Only keycloak is added to etc/hosts to make it less confusing
- URL patterns are automatically added from each extensions' urls.py file
- CI Docker and Python tests are run in parallel

An example setup is given in https://github.com/MILA-Wien/collectivo-quickstart

The basic idea is that configuration data flows from one layer to the next:

- docker-compose.yml can read secret variables from .env
- collectivo.yml can read environmental variables from docker-compose.yml
- settings.py can read data from collectivo.yml
- extensions can read data from settings.py

The objective is that most users will only have to edit things in .env and collectivo.yml

2023-06-01 19:48 UTC, nanu-c requested changes
Well done, i have some clarification questions but no general objections ;)

2023-06-01 19:48 UTC, nanu-c commented on README.md
> +- Add the following line to your `/etc/hosts/` file: `127.0.0.1 keycloak 127.0.0.1`
this change is wrong, when we don't use `collectivo.local` then just remove it

2023-06-01 19:48 UTC, nanu-c commented on collectivo/components/views.py
> +    permission_classes = [IsSuperuser]
couldn't this be a problem if a normal user want's to query the components to show them?

2023-06-01 19:48 UTC, nanu-c commented on collectivo/core/models.py
> +    # project_logo = models.ImageField(
the direktkredit plattform has here the possibility to define also an external url for the logo. So maybe that could be added, too.

2023-06-01 19:48 UTC, nanu-c commented on collectivo/core/serializers.py
> +    # TODO: Get through groups
can you define the todo a little bit more specific? Or isn't this really important so that permissions can be inherited by a group membership?

2023-06-01 19:48 UTC, nanu-c commented on collectivo/core/serializers.py
> +
How should we proceed with the todos? Should we track them also somewhere else?

2023-06-01 19:48 UTC, nanu-c commented on collectivo/core/views.py
> +class HealthView(APIView):
cool :)

2023-06-01 19:48 UTC, nanu-c commented on collectivo/emails/setup.py
> +        requires_perm=("admin", "core"),
Is this `or` or `and`?

2023-06-01 19:48 UTC, nanu-c commented on collectivo/memberships/views.py
> +    required_perms = ["collectivo.memberships.admin"]
for me the differentiation between group and permission isn't clear. i would rather add a user to a group than "finetune" the permissions for the user. So somehow we should keep the "HasGroup" together with the new "hasPerm"? So the developer of an addon can either choose a group or a permission?

2023-06-01 19:48 UTC, nanu-c commented on collectivo/utils/permissions.py
> +            groups__in=user.permission_groups.all(),
okey i see

2023-06-01 19:48 UTC, nanu-c commented on collectivo/utils/viewsets.py
> +class CoViewSet(HistoryMixin, SchemaMixin, GenericViewSet):
Why do you introduce the `Co` as shortener for `Collectivo`. I am always for the longer version that is better understandable.

2023-06-01 19:48 UTC, nanu-c commented on collectivo_app/collectivo_app/settings.py
> +    *COLLECTIVO["extensions"],
Nice :)

2023-06-01 19:48 UTC, nanu-c commented on collectivo_app/collectivo_app/urls.py
> +        logger.error(f"Error reading urls.py for {app}: {e}", exc_info=True)
Nice number 2 :)

2023-06-01 19:48 UTC, nanu-c commented on collectivo_app/collectivo_app/utils.py
> +                    extensions[ext_name][key] = value
This part is not very clear and quite complex. Can you document it a little bit more?

2023-06-01 19:48 UTC, nanu-c commented on docker-compose.yml
>        - ./docker/static:/collectivo_app/static
I would mention the collectivo.yml here, too

2023-06-01 19:48 UTC, nanu-c commented on docs/extensions/keycloak.md
> +```
I would mention what happens, when keycloak is not configured.

2023-06-01 19:48 UTC, nanu-c commented on docs/extensions/overview.md
> +    - [Shifts](shifts.md) - Organize working shifts and teams
Maybe add Lotz app as third party extension?

2023-06-02 08:43 UTC, JoelForamitti commented on README.md
> +- Add the following line to your `/etc/hosts/` file: `127.0.0.1 keycloak 127.0.0.1`
Done!

2023-06-02 08:44 UTC, JoelForamitti commented on collectivo/components/views.py
> +    permission_classes = [IsSuperuser]
True! I have changed so that reading is possible for all authenticated users.

2023-06-02 08:45 UTC, JoelForamitti commented on collectivo/core/models.py
> +    # project_logo = models.ImageField(
Good idea! I will include it in the PR that implements the Logo

2023-06-02 08:47 UTC, JoelForamitti commented on collectivo/core/serializers.py
> +    # TODO: Get through groups
I have changed it to `Display all permissions of the user based on their groups`.

Generally, you can only get permissions through group membership at the moment. The TODO is because the serializer currently only shows the groups but it would be nice to get a list of all permissions inherited from those groups.

2023-06-02 08:52 UTC, JoelForamitti commented on collectivo/core/serializers.py
> +
I'd say the Userprofiles Serializer as a whole is an open TODO to be improved. At the moment I track the todos personally. I would suggest once this intensive development phase of June is over that I will write up the remaining TODOs on a shared board again. Does that sound good?

2023-06-02 08:55 UTC, JoelForamitti commented on collectivo/emails/setup.py
> +        requires_perm=("admin", "core"),
It is refers to only one permission, the tuple indicates the name of the permission and the name of the extension. This is to avoid name-conflicts between different extensions.

2023-06-02 08:56 UTC, JoelForamitti commented on collectivo/memberships/views.py
> +    required_perms = ["collectivo.memberships.admin"]
My approach was the following:

- Only permissions can be used to allow/deny access.
- Permissions can be added to groups.
- Groups can be added to users.

Does that sound good?

2023-06-02 08:59 UTC, JoelForamitti commented on collectivo/utils/viewsets.py
> +class CoViewSet(HistoryMixin, SchemaMixin, GenericViewSet):
You are right, I changed it back to collectivo.

2023-06-02 09:09 UTC, JoelForamitti commented on collectivo_app/collectivo_app/utils.py
> +                    extensions[ext_name][key] = value
I have extended the docstring:

    Create a dictionary of extension configs.

    Configurations are taken from the raw yaml input
    of both collectivo.yml and each extensions' extension.yml.

    Deals with the fact that yaml entries are converted to different data
    types. Tries to capture common cases to ensure that the resulting
    extension configs are nested dictionaries.

    Extensions that do not exist as python modules are removed.

2023-06-02 09:11 UTC, JoelForamitti commented on docker-compose.yml
>        - ./docker/static:/collectivo_app/static
Done

2023-06-02 09:12 UTC, JoelForamitti commented on docs/extensions/keycloak.md
> +```
I added:

    When keycloak is not correctly configured, a warning will appear in the logs.

2023-06-05 10:01 UTC, nanu-c approved these changes

2023-06-09 08:42 UTC, nanu-c approved these changes

2023-06-12 13:09 UTC, merged