Extensions, Microfrontends, and Menus API
MILA-Wien/collectivo pull request #12
Opened 2022-10-10 12:16 UTC by JoelForamitti

This PR adds first functionalities for extensions. 
- A UX extension that provides an API call to load menu items.
- A way for extensions to include themselves in the URL patterns.
- A way to build microfrontend components and serve them as static files.

2022-10-11 13:47 UTC, JoelForamitti commented
There is now a webcomponent in the test_extension. If yarn build is used, the dist files are copied to the static folder. In debug mode, the static files can be accessed e.g. via `localhost:8000/static/test_extension/ux/dist/index.html`.

2022-10-13 10:27 UTC, JoelForamitti commented
There is now a new menu API to load menu items at `/api/collectivo.ux/v1/menu/{menu_name}`.
There is currently one menu `main_menu` which we can use.

2022-10-19 13:43 UTC, JoelForamitti commented
There is now an API to manage extensions and microfrontends

2022-10-20 09:04 UTC, JoelForamitti commented
There is now an API to manage menus

2022-10-24 08:27 UTC, nanu-c requested changes
Well done, just 2 little remarks

2022-10-24 08:27 UTC, nanu-c commented on collectivo-test-app/test_extension/menus.py
> +# from collectivo.ux.menus import main_menu, MenuItem
Isn't it working or why is the menu commented?

2022-10-24 08:27 UTC, nanu-c commented on collectivo/urls.py
> +if settings.DEBUG:
static files only when `DEBUG` is true? Shouldn't we rename it to something else?

2022-10-24 08:29 UTC, JoelForamitti commented on collectivo/urls.py
> +if settings.DEBUG:
they say in the django docs that this trick should only be used for development, and that the static files should be served over e.g. the nginx server in production

yes, we can rename it if you want!

2022-10-24 08:31 UTC, nanu-c commented on collectivo/urls.py
> +if settings.DEBUG:
Ah , yes, I have already done this here https://github.com/MILA-Wien/collectivo/blob/main/docker-compose.yml#L38

2022-10-24 08:32 UTC, nanu-c commented on collectivo/urls.py
> +if settings.DEBUG:
But i would rename it to development or smth. like this.

2022-10-24 08:33 UTC, JoelForamitti commented on collectivo-test-app/test_extension/menus.py
> +# from collectivo.ux.menus import main_menu, MenuItem
ah, this file is deprecated. the menu is now added via API call in apps.py. I will clean up the test_extension in a future PR.

2022-10-24 08:48 UTC, nanu-c approved these changes

2022-10-24 08:51 UTC, merged