History
MILA-Wien/collectivo pull request #130
Opened 2023-07-06 15:27 UTC by JoelForamitti

- Change logic from revert to restore
- Add track changes

2023-07-10 20:13 UTC, nanu-c commented on collectivo/core/tests/test_core.py
> +            keycloak.delete_user_by_email("456@example.com")
Isn't it better to make something like keycloak.update_user_email_by_email("old@email","new@email")?

2023-07-10 20:32 UTC, nanu-c requested changes

2023-07-10 20:32 UTC, nanu-c commented on collectivo/core/tests/test_core.py
> +            keycloak.delete_user_by_email("456@example.com")
or is this for reusing the same email for the tests?

2023-07-10 20:32 UTC, nanu-c commented on collectivo/utils/serializers.py
> +                return format_html(fields)
I will accept this now, but actually the backend shouldn't deliver html code. Let the frontend do the magic and define a dict/type/struct that is then rendered.

2023-07-10 20:32 UTC, nanu-c commented on docs/extensions/components.md
> +
I would add here, that all js frameworks that are supported by vite can be used, namely vue, react, svelte and more.

2023-07-10 20:32 UTC, nanu-c commented on docs/extensions/payments.md
> +Manage payment methods, invoices, and subscriptions.
Maybe add "This doesn't include a payment provider yet, so invoices are sent by email." Should we mention Lotzapp here?

2023-07-10 20:32 UTC, nanu-c commented on docs/extensions/tags.md
> +Add tags to users.
Tags can be used for any kind of clustering, filtering or automation and can be highly adopted to internal processes of your organisation.

2023-07-10 20:32 UTC, nanu-c commented on docs/reference.md
> +This section providefs a technical description of Collectivo's models and functions.
`provides`

2023-07-10 20:32 UTC, nanu-c commented on docs/reference.md
> +An automated API documentation of your own instance can be found under the `<your-backend-url>/api/docs`.
When the extension `api_docs` is enabled.

2023-07-11 07:21 UTC, JoelForamitti commented on collectivo/core/tests/test_core.py
> +            keycloak.delete_user_by_email("456@example.com")
This is because the test case does not reset the keycloak database. So if the last test created 123 and changed it to 456, there remains a remnant 456 email in the keycloack database. The next test is then not able to change 123 to 456 because 456 already exists.

2023-07-11 07:22 UTC, JoelForamitti commented on collectivo/utils/serializers.py
> +                return format_html(fields)
Yes, let us define a better structure. I have put this on the todo list

2023-07-11 07:25 UTC, JoelForamitti commented on docs/extensions/components.md
> +
done

2023-07-11 07:29 UTC, JoelForamitti commented on docs/extensions/payments.md
> +Manage payment methods, invoices, and subscriptions.
Well, we also do not have a feature for mails yet. I have added a sentence about the missing payment provider and lotzapp.

2023-07-11 07:32 UTC, JoelForamitti commented on docs/extensions/tags.md
> +Add tags to users.
Perfect!

2023-07-11 07:32 UTC, JoelForamitti commented on docs/reference.md
> +This section providefs a technical description of Collectivo's models and functions.
fixed!

2023-07-11 07:33 UTC, JoelForamitti commented on docs/reference.md
> +An automated API documentation of your own instance can be found under the `<your-backend-url>/api/docs`.
done!

2023-07-11 10:07 UTC, nanu-c approved these changes

2023-07-11 13:56 UTC, merged