Shifts model
MILA-Wien/collectivo pull request #66
Opened 2023-02-03 16:08 UTC by lebe1

- adds a model for shift management

2023-02-21 08:01 UTC, JoelForamitti commented
Somehow the CI has been disabled with the last commit

2023-02-24 10:21 UTC, nanu-c requested changes

2023-02-24 10:21 UTC, nanu-c commented on collectivo/shifts/views.py
> +    # Unsupported lookup 'icontains' for CharField
Is this still relevant?

2023-02-24 10:21 UTC, nanu-c commented on collectivo/shifts/tests/test_shifts.py
> +        # self.assertEqual(res.data[1]["shift_starting_date"], "2023-09-04")
either delete it or fix it or explain why it's commented.

2023-02-24 10:21 UTC, nanu-c commented on collectivo/shifts/utils.py
> +
Are the utils still in use?

2023-02-24 12:23 UTC, lebe1 commented on collectivo/shifts/views.py
> +            raise ValidationError("Missing attribute 'shift_ending_date'")
Good found! Important though to mention, that gte (<=) and lte (>=) always has to be asked in the frontend since in the backend in these [if-clauses](https://github.com/MILA-Wien/collectivo/blob/fe80114dd24f933e6040d7f35299eac14c68cbfe/collectivo/shifts/views.py#L105-L118) I ask for `>` and `<`.
Not quite sure where or if we should document it somewhere or if it is enough implementing it right, What do you think?

2023-02-24 12:34 UTC, lebe1 commented on collectivo/shifts/views.py
> +            raise ValidationError("Missing attribute 'shift_ending_date'")
I have to correct myself. It raises a value error if I remove `__lte` and `__gte` since I'm asking for the same attribute. 
The whole logic is build upon this, which I forgot to explain in detail.
I am always asking for `shift_starting_date` since an unique shift just requires to have a `shift_starting_date`. 
Also it is possible to create a regular shift without adding the attribute `shift_ending_date`, which means this shift goes on forever.

2023-02-24 12:42 UTC, lebe1 commented on collectivo/shifts/tests/test_shifts.py
> +        # self.assertEqual(res.data[1]["shift_starting_date"], "2023-09-04")
Explained it. If you disagree to keep these comments, I don't mind deleting them.

2023-03-07 11:43 UTC, nanu-c approved these changes

2023-03-07 11:43 UTC, merged