Custom tiles
MILA-Wien/collectivo pull request #92
Opened 2023-04-07 16:33 UTC by JoelForamitti

This PR makes it possible for admins to create custom dashboard tiles.

2023-04-11 09:02 UTC, nanu-c requested changes

2023-04-11 09:02 UTC, nanu-c commented on collectivo/dashboard/models.py
> +    )
Please add an enabled/disabled field

2023-04-11 16:40 UTC, JoelForamitti commented on collectivo/dashboard/models.py
> +    )
great suggestion! done

2023-04-12 08:11 UTC, nanu-c approved these changes

2023-04-12 08:11 UTC, merged